Nft docs
PolymeshAssociation/polymesh-documentation-site pull request #31
Opened 2023-09-20 22:39 UTC by HenriqueNogara

Adds a simple documentation page for the NFT pallet

2023-09-22 16:52 UTC, F-OBrien requested changes
Minor comments but otherwise LGTM

2023-09-22 16:52 UTC, F-OBrien commented on polymesh-docs/primitives/nfts.mdx
> +# Non-Fungible Token
```suggestion
# Non-Fungible Tokens 
```

2023-09-22 16:52 UTC, F-OBrien commented on polymesh-docs/primitives/nfts.mdx
> +The NFT pallet extends the Asset pallet allowing users to create NFT collections, issue unique tokens and redeem (i.e. burn) existing non-fungible tokens. The documentation for the NFT crate can be f
```suggestion
The Non-Fungible Token (NFT) pallet extends the Asset pallet allowing users to create NFT collections, issue unique tokens and redeem (i.e. burn) existing non-fungible tokens. The documentation for the NFT crate can be found [here](https://docs.polymesh.live/pallet_nft/index.html).
```

2023-09-22 16:52 UTC, F-OBrien commented on polymesh-docs/primitives/nfts.mdx
> +* If the asset already exists, it must be of type `NonFungible` and the caller must have the proper permission for the asset. Otherwise, the `create_nft_collection` dispatchable will also create one
```suggestion
* If the asset already exists, it must be of type `NonFungible` and the caller must have the proper permission for the asset. If the asset does not already exist, the `create_nft_collection` dispatchable will also create one non-fungible asset using the values passed as `ticker` and `nft_type`; 
```

2023-09-22 16:52 UTC, F-OBrien commented on polymesh-docs/primitives/nfts.mdx
> +* All metadata keys must be registered. This implies that when using local metadata keys, one must call `create_asset` and `register_asset_metadata_local_type` before calling `create_nft_collection`;
```suggestion
* All metadata keys must be registered prior to the creation of the collection. This implies that when using local metadata keys, one must call `create_asset` and `register_asset_metadata_local_type` before calling `create_nft_collection`;
```

2023-09-22 16:52 UTC, F-OBrien commented on polymesh-docs/primitives/nfts.mdx
> +* All metadata keys specified in the NFT collection must be set when issuing the token. Attempting to issue a token with metadata keys not defined in the collection will also fail;
```suggestion
* All metadata keys specified in the NFT collection must have a value set when issuing the token. Attempting to issue a token with metadata keys not defined in the collection will also fail;
```

2023-10-04 14:27 UTC, adamdossa approved these changes

2023-10-04 14:27 UTC, merged